import { describe, expect, it } from "vitest";
import {
  groupStatus,
  deriveTitle,
  canReadPrompt,
  deriveViewMode,
  buildSessionRows,
  filterRows,
  expandSessionRow,
  deriveDetailSections,
  pollIntervalMs,
  shouldPoll,
  preferSnapshot,
  resolveScope,
  filterTasksByScope,
  formatElapsed,
  isStale,
  deriveActivityLabel,
  deriveTimeline,
  deriveLatestUpdate,
} from "./state.js";

function task(overrides = {}) {
  return {
    taskId: "task-1",
    jobId: "task-1",
    sessionKey: "session-1",
    agent: "clawdy",
    status: "running",
    startedAt: 1000,
    lastEventAt: 1500,
    ...overrides,
  };
}

describe("groupStatus — display bucketing preserves exact status", () => {
  it("maps every TaskStatus to exactly one of the four human groups", () => {
    expect(groupStatus("running")).toBe("active");
    expect(groupStatus("queued")).toBe("active");
    expect(groupStatus("blocked")).toBe("needs_attention");
    expect(groupStatus("needs-human")).toBe("needs_attention");
    expect(groupStatus("done")).toBe("completed");
    expect(groupStatus("failed")).toBe("failed");
  });

  it("grouping is a pure derived view — the underlying task object is never mutated", () => {
    const t = task({ status: "blocked" });
    const before = JSON.stringify(t);
    groupStatus(t.status);
    expect(JSON.stringify(t)).toBe(before);
    expect(t.status).toBe("blocked"); // exact status preserved, not rewritten to "needs_attention"
  });
});

describe("deriveTitle — generated by default, never from the prompt", () => {
  it("prefers a PR/branch label when artifacts have one", () => {
    expect(deriveTitle(task({ artifacts: { prUrl: "https://x/pull/1", branchName: "fix/thing" } }))).toBe("PR: fix/thing");
  });

  it("falls back to the agent reply summary, truncated", () => {
    expect(deriveTitle(task({ status: "done", summary: "Fixed the login bug and added tests." }))).toBe(
      "Fixed the login bug and added tests.",
    );
    const long = "x".repeat(100);
    expect(deriveTitle(task({ status: "done", summary: long }))).toHaveLength(64);
  });

  it("uses an agent+status label while running with no summary yet", () => {
    expect(deriveTitle(task({ status: "running", summary: undefined }))).toBe("clawdy is working…");
  });

  it("falls back to a short task id as a last resort", () => {
    expect(deriveTitle(task({ status: "done", summary: undefined, taskId: "abcdef1234567890" }))).toBe("Task abcdef12");
  });

  it("never references the stored prompt field — the function signature doesn't even accept one", () => {
    // Structural guarantee: deriveTitle takes a task/snapshot, which per the
    // core contract never carries a `prompt` field (see getTaskPrompt's
    // separate return type in packages/core/src/types.ts). Passing one in
    // anyway must not leak into the title.
    const withPrompt = task({ status: "done", summary: undefined, prompt: { task: "the real secret ask" } });
    expect(deriveTitle(withPrompt)).not.toContain("secret");
  });
});

describe("canReadPrompt — gates the dedicated authorized prompt-reader action", () => {
  it("true whenever a taskId/jobId is resolvable", () => {
    expect(canReadPrompt(task())).toBe(true);
    expect(canReadPrompt(task({ taskId: undefined, jobId: "job-2" }))).toBe(true);
  });

  it("false for a row with no resolvable id — the action must not render", () => {
    expect(canReadPrompt(task({ taskId: undefined, jobId: undefined }))).toBe(false);
    expect(canReadPrompt(undefined)).toBe(false);
  });
});

describe("deriveViewMode — aggregate command center collapsing to a focused single task", () => {
  it("collapses to focused when the mounted session is the only one with active work", () => {
    const mounted = { taskId: "task-1", sessionKey: "session-1" };
    const tasks = [task({ status: "running" })];
    expect(deriveViewMode(mounted, tasks)).toEqual({ mode: "focused", taskId: "task-1", sessionKey: "session-1" });
  });

  it("collapses to focused when other sessions exist but are all terminal", () => {
    const mounted = { taskId: "task-1", sessionKey: "session-1" };
    const tasks = [
      task({ status: "running" }),
      task({ taskId: "task-2", jobId: "task-2", sessionKey: "session-2", status: "done" }),
    ];
    expect(deriveViewMode(mounted, tasks).mode).toBe("focused");
  });

  it("renders aggregate, with the mounted session highlighted, when multiple sessions have active work", () => {
    const mounted = { taskId: "task-1", sessionKey: "session-1" };
    const tasks = [
      task({ status: "running" }),
      task({ taskId: "task-2", jobId: "task-2", sessionKey: "session-2", status: "blocked" }),
    ];
    expect(deriveViewMode(mounted, tasks)).toEqual({ mode: "aggregate", highlightSessionKey: "session-1" });
  });

  it("renders aggregate with no highlight when nothing is mounted (e.g. a stand-alone list_tasks view)", () => {
    expect(deriveViewMode(undefined, [task()])).toEqual({ mode: "aggregate", highlightSessionKey: undefined });
  });

  it("handles an empty task list gracefully (missing-metadata-shaped edge case)", () => {
    expect(deriveViewMode({ taskId: "t", sessionKey: "s" }, []).mode).toBe("focused");
    expect(deriveViewMode(undefined, []).mode).toBe("aggregate");
  });
});

describe("buildSessionRows — session-first rows keyed by sessionKey", () => {
  it("collapses multiple tasks in the same session to one row, keeping the most recent", () => {
    const tasks = [
      task({ taskId: "t1", jobId: "t1", lastEventAt: 1000, status: "done" }),
      task({ taskId: "t2", jobId: "t2", lastEventAt: 2000, status: "running" }),
    ];
    const rows = buildSessionRows(tasks);
    expect(rows).toHaveLength(1);
    expect(rows[0].latestTask.taskId).toBe("t2");
  });

  it("sorts by recency, newest first, with the highlighted session pinned to the top", () => {
    const rows = buildSessionRows(
      [
        task({ sessionKey: "old", lastEventAt: 1000 }),
        task({ sessionKey: "new", lastEventAt: 5000 }),
        task({ sessionKey: "mounted", lastEventAt: 500 }),
      ],
      { highlightSessionKey: "mounted" },
    );
    expect(rows.map((r) => r.sessionKey)).toEqual(["mounted", "new", "old"]);
  });

  it("marks the highlighted row expanded by default; others unexpanded", () => {
    const rows = buildSessionRows([task({ sessionKey: "a" }), task({ sessionKey: "b" })], { highlightSessionKey: "a" });
    expect(rows.find((r) => r.sessionKey === "a")?.expanded).toBe(true);
    expect(rows.find((r) => r.sessionKey === "b")?.expanded).toBe(false);
  });
});

describe("filterRows — Active default view + Recent view, exact status preserved underneath", () => {
  const rows = buildSessionRows([
    task({ sessionKey: "a", status: "running", lastEventAt: 3000 }),
    task({ sessionKey: "b", status: "blocked", lastEventAt: 2000 }),
    task({ sessionKey: "c", status: "done", lastEventAt: 1000 }),
    task({ sessionKey: "d", status: "failed", lastEventAt: 500 }),
  ]);

  it('"active" view (default) shows only Active + Needs attention groups', () => {
    const active = filterRows(rows, "active");
    expect(active.map((r) => r.sessionKey).sort()).toEqual(["a", "b"]);
  });

  it('"recent" view shows every group, and the underlying task.status is untouched', () => {
    const recent = filterRows(rows, "recent");
    expect(recent).toHaveLength(4);
    expect(recent.find((r) => r.sessionKey === "d")?.latestTask.status).toBe("failed");
  });
});

describe("expandSessionRow — expandable task history keyed by taskId", () => {
  it("attaches history from get_session(mode:\"tasks\"), grouped per entry, without touching the row's own fields", () => {
    const row = buildSessionRows([task({ sessionKey: "s", status: "running" })])[0];
    const history = [
      task({ taskId: "t1", jobId: "t1", sessionKey: "s", status: "done", summary: "first" }),
      task({ taskId: "t2", jobId: "t2", sessionKey: "s", status: "running" }),
    ];
    const expanded = expandSessionRow(row, history);
    expect(expanded.expanded).toBe(true);
    expect(expanded.history).toHaveLength(2);
    expect(expanded.history[0].group).toBe("completed");
    expect(expanded.history[0].title).toBe("first");
    expect(expanded.sessionKey).toBe(row.sessionKey);
  });
});

describe("deriveDetailSections — context-aware, read-only detail rendering", () => {
  it("shows only sections the task actually has data for", () => {
    expect(deriveDetailSections(task({ status: "running", summary: undefined }))).toEqual(["status", "liveUpdate"]);
    expect(deriveDetailSections(task({ status: "done", summary: "done!" }))).toEqual(["status", "summary"]);
    expect(
      deriveDetailSections(task({ status: "error", error: "boom", errorInfo: { category: "unknown" } })),
    ).toContain("error");
    expect(
      deriveDetailSections(task({ status: "done", artifacts: { filesChanged: ["a.ts"], commandsRun: [] } })),
    ).toContain("artifacts");
  });

  it("never includes an action/mutation section — read-only, navigation only", () => {
    const sections = deriveDetailSections(task({ status: "done", summary: "x", artifacts: { prUrl: "y" } }));
    expect(sections).not.toContain("cancel");
    expect(sections).not.toContain("mutate");
  });
});

describe("bounded + deduplicated reads", () => {
  it("pollIntervalMs follows the attention-shaped cadence and stops at any terminal group", () => {
    expect(pollIntervalMs("active")).toBe(2500);
    expect(pollIntervalMs("needs_attention")).toBe(8000);
    expect(pollIntervalMs("completed")).toBeNull();
    expect(pollIntervalMs("failed")).toBeNull();
  });

  it("pollIntervalMs backs off on repeated failures, capped at 30s", () => {
    expect(pollIntervalMs("active", 1)).toBe(5000);
    expect(pollIntervalMs("active", 10)).toBe(30000);
  });

  it("shouldPoll refuses to start a second read while one is already in flight (dedup)", () => {
    expect(shouldPoll({ pollInFlight: true, tasks: [task({ status: "running" })] })).toBe(false);
  });

  it("shouldPoll stops once every task in scope is terminal (bound)", () => {
    expect(shouldPoll({ pollInFlight: false, tasks: [task({ status: "done" }), task({ status: "failed" })] })).toBe(false);
  });

  it("shouldPoll allows one read when nothing is known yet, and continues while anything is non-terminal", () => {
    expect(shouldPoll({ pollInFlight: false, tasks: [] })).toBe(true);
    expect(shouldPoll({ pollInFlight: false, tasks: [task({ status: "running" })] })).toBe(true);
  });

  it("preferSnapshot never lets a stale non-terminal read overwrite an already-terminal one", () => {
    const terminal = task({ status: "done", lastEventAt: 1000 });
    const staleRunning = task({ status: "running", lastEventAt: 5000 }); // newer timestamp, but non-terminal
    expect(preferSnapshot(staleRunning, terminal)).toBe(terminal);
  });

  it("preferSnapshot prefers the newer of two non-terminal (or two terminal) reads", () => {
    const older = task({ status: "running", lastEventAt: 1000 });
    const newer = task({ status: "running", lastEventAt: 2000 });
    expect(preferSnapshot(newer, older)).toBe(newer);
    expect(preferSnapshot(older, newer)).toBe(newer);
  });

  it("preferSnapshot with no current snapshot just takes the first read", () => {
    const first = task();
    expect(preferSnapshot(first, undefined)).toBe(first);
  });
});

describe("conversation scope fallback", () => {
  it("defaults to this card instance's own known sessions, not a true conversation-wide claim", () => {
    const scope = resolveScope(["s1", "s2", "s1"], false);
    expect(scope).toEqual({ scoped: true, sessionKeys: ["s1", "s2"] });
    const tasks = [task({ sessionKey: "s1" }), task({ sessionKey: "s3" })];
    expect(filterTasksByScope(tasks, scope).map((t) => t.sessionKey)).toEqual(["s1"]);
  });

  it("explicit All activity opts out of scoping entirely", () => {
    const scope = resolveScope(["s1"], true);
    expect(scope).toEqual({ scoped: false, sessionKeys: null });
    const tasks = [task({ sessionKey: "s1" }), task({ sessionKey: "unrelated" })];
    expect(filterTasksByScope(tasks, scope)).toHaveLength(2);
  });
});

describe("formatElapsed", () => {
  it("formats seconds, minutes, and hours", () => {
    expect(formatElapsed(5_000)).toBe("5s");
    expect(formatElapsed(90_000)).toBe("1m 30s");
    expect(formatElapsed(3 * 60 * 60_000 + 5 * 60_000)).toBe("3h 5m");
  });

  it("handles zero/negative/non-finite gracefully rather than throwing", () => {
    expect(formatElapsed(0)).toBe("0s");
    expect(formatElapsed(-5)).toBe("0s");
    expect(formatElapsed(NaN)).toBe("0s");
  });
});

describe("isStale / deriveActivityLabel — a liveness claim paired with the evidence behind it", () => {
  it("is not stale within the threshold, stale beyond it", () => {
    const now = 100_000;
    expect(isStale(now - 10_000, now)).toBe(false);
    expect(isStale(now - 91_000, now)).toBe(true);
  });

  it("an active task well within the threshold reads as active, with elapsed time as evidence", () => {
    const now = 100_000;
    expect(deriveActivityLabel(task({ status: "running", lastEventAt: now - 5_000 }), now)).toBe("active 5s ago");
  });

  it("an active task past the stale threshold is flagged as possibly stuck — this is what makes \"is working\" trustworthy or not", () => {
    const now = 200_000;
    expect(deriveActivityLabel(task({ status: "running", lastEventAt: now - 120_000 }), now)).toBe(
      "quiet for 2m 0s — may be stuck",
    );
  });

  it("a terminal task reads as finished, not active/stale", () => {
    const now = 100_000;
    expect(deriveActivityLabel(task({ status: "done", lastEventAt: now - 5_000 }), now)).toBe("finished 5s ago");
  });
});

describe("deriveTimeline / deriveLatestUpdate — the actual evidence, not just a status label", () => {
  const logs = [
    { ts: 1000, type: "lifecycle", text: "Started" },
    { ts: 1200, type: "tool", text: "Reading files" },
    { ts: 1400, type: "tool", text: "Reading files" },
    { ts: 1600, type: "tool", text: "Reading files" },
    { ts: 1800, type: "tool-result", text: "3 files read" },
    { ts: 2000, type: "tool", text: "Running command: pnpm test" },
  ];

  it("collapses consecutive identical entries into one row with a count, instead of spamming duplicates", () => {
    const timeline = deriveTimeline(logs, 10);
    const readingFiles = timeline.find((row) => row.text === "Reading files");
    expect(readingFiles?.count).toBe(3);
  });

  it("returns at most maxRows, most recent first", () => {
    const timeline = deriveTimeline(logs, 2);
    expect(timeline).toHaveLength(2);
    expect(timeline[0].text).toBe("Running command: pnpm test");
  });

  it("returns an empty array for missing/empty logs rather than throwing", () => {
    expect(deriveTimeline(undefined)).toEqual([]);
    expect(deriveTimeline([])).toEqual([]);
  });

  it("deriveLatestUpdate returns the single most recent entry", () => {
    expect(deriveLatestUpdate(logs)).toEqual({ ts: 2000, type: "tool", text: "Running command: pnpm test" });
    expect(deriveLatestUpdate([])).toBeNull();
  });
});
