import { describe, expect, it } from "vitest";
import {
  groupStatus,
  deriveTitle,
  canReadPrompt,
  deriveViewMode,
  buildSessionRows,
  filterRows,
  expandSessionRow,
  mergePinnedDetail,
  ensurePinnedTask,
  isTaskSnapshot,
  deriveCardTabs,
  defaultCardTab,
  isLikelyMarkdown,
  renderMarkdownHtml,
  pollIntervalMs,
  shouldPoll,
  preferSnapshot,
  resolveScope,
  filterTasksByScope,
  resolveCompactSelection,
  reconcileTaskList,
  formatElapsed,
  isStale,
  deriveActivityLabel,
  deriveTimeline,
  deriveLatestUpdate,
  deriveStatusPill,
  deriveConnectionNotice,
  deriveCounts,
  formatCounts,
  nextCardTab,
  mergeRingBuffer,
  RING_BUFFER_MAX,
  shouldRenderImmediately,
  collectFollowUpWakes,
  deriveDelegationIdentity,
  deriveUpstreamEvidence,
  normalizeDiagnostics,
} from "./state.js";

function task(overrides = {}) {
  return {
    taskId: "task-1",
    jobId: "task-1",
    sessionKey: "session-1",
    agent: "assistant",
    status: "running",
    startedAt: 1000,
    lastEventAt: 1500,
    ...overrides,
  };
}

describe("groupStatus — display bucketing preserves exact status", () => {
  it("maps every TaskStatus to exactly one of the four human groups", () => {
    expect(groupStatus("running")).toBe("active");
    expect(groupStatus("queued")).toBe("active");
    expect(groupStatus("blocked")).toBe("needs_attention");
    expect(groupStatus("needs-human")).toBe("needs_attention");
    expect(groupStatus("done")).toBe("completed");
    expect(groupStatus("completed")).toBe("completed");
    expect(groupStatus("completed_no_summary")).toBe("completed");
    expect(groupStatus("failed")).toBe("failed");
  });

  it("keeps the exact completed get_task shape successful even after lifecycle:end", () => {
    const completed = task({
      status: "completed",
      isError: false,
      isTerminal: true,
      logs: [{ type: "lifecycle", text: "Agent lifecycle: end", ts: 2000 }],
    });
    expect(groupStatus(completed.status)).toBe("completed");
    expect(deriveStatusPill(groupStatus(completed.status))).toEqual({ icon: "✓", label: "Completed" });
  });

  it("grouping is a pure derived view — the underlying task object is never mutated", () => {
    const t = task({ status: "blocked" });
    const before = JSON.stringify(t);
    groupStatus(t.status);
    expect(JSON.stringify(t)).toBe(before);
    expect(t.status).toBe("blocked"); // exact status preserved, not rewritten to "needs_attention"
  });
});

describe("deriveTitle — generated by default, never from the prompt", () => {
  it("prefers a PR/branch label when artifacts have one", () => {
    expect(deriveTitle(task({ artifacts: { prUrl: "https://x/pull/1", branchName: "fix/thing" } }))).toBe("PR: fix/thing");
  });

  it("falls back to the agent reply summary, truncated", () => {
    expect(deriveTitle(task({ status: "done", summary: "Fixed the login bug and added tests." }))).toBe(
      "Fixed the login bug and added tests.",
    );
    const long = "x".repeat(100);
    expect(deriveTitle(task({ status: "done", summary: long }))).toHaveLength(64);
  });

  it("uses an agent+status label while running with no summary yet", () => {
    expect(deriveTitle(task({ status: "running", summary: undefined }))).toBe("assistant is working…");
  });

  it("falls back to a short task id as a last resort", () => {
    expect(deriveTitle(task({ status: "done", summary: undefined, taskId: "abcdef1234567890" }))).toBe("Task abcdef12");
  });

  it("labels blocked/needs-human by their actual status, not \"Task failed\" — regression: core sets .error to a session-busy message for status=\"blocked\" (deriveTaskStatus in packages/core/src/tools.ts), which used to make deriveTitle key off .error truthiness and mislabel it as failed; caught by browser smoke test, not by the unit suite, because no prior fixture combined a non-failed status with a truthy .error", () => {
    expect(deriveTitle(task({ status: "blocked", summary: undefined, error: "session busy" }))).toBe("Blocked");
    expect(deriveTitle(task({ status: "needs-human", summary: undefined, error: "needs input" }))).toBe("Needs your input");
    expect(deriveTitle(task({ status: "failed", summary: undefined, error: "boom" }))).toBe("Task failed");
  });

  it("uses a markdown summary's own heading as the title rather than showing literal ## / ** syntax — caught in a browser screenshot once summaries began rendering as real markdown", () => {
    const summary = "## What changed\n\nReworked the reconnect path. The **stale jobId** was the root cause; see `resolveJob()`.";
    expect(deriveTitle(task({ status: "done", summary }))).toBe("What changed");
  });

  it("strips inline markdown from a summary with no heading, without cutting a hard-wrapped one at its first newline", () => {
    expect(deriveTitle(task({ status: "done", summary: "Fixed the **stale** `jobId`\nand added coverage." }))).toBe(
      "Fixed the stale jobId and added coverage.",
    );
    expect(deriveTitle(task({ status: "done", summary: "See [the PR](https://x/pull/1) for details." }))).toBe("See the PR for details.");
    expect(deriveTitle(task({ status: "done", summary: "- shipped it" }))).toBe("shipped it");
  });

  it("never references the stored prompt field — the function signature doesn't even accept one", () => {
    // Structural guarantee: deriveTitle takes a task/snapshot, which per the
    // core contract never carries a `prompt` field (see getTaskPrompt's
    // separate return type in packages/core/src/types.ts). Passing one in
    // anyway must not leak into the title.
    const withPrompt = task({ status: "done", summary: undefined, prompt: { task: "the real secret ask" } });
    expect(deriveTitle(withPrompt)).not.toContain("secret");
  });
});

describe("canReadPrompt — gates the dedicated authorized prompt-reader action", () => {
  it("true whenever a taskId/jobId is resolvable", () => {
    expect(canReadPrompt(task())).toBe(true);
    expect(canReadPrompt(task({ taskId: undefined, jobId: "job-2" }))).toBe(true);
  });

  it("false for a row with no resolvable id — the action must not render", () => {
    expect(canReadPrompt(task({ taskId: undefined, jobId: undefined }))).toBe(false);
    expect(canReadPrompt(undefined)).toBe(false);
  });
});

describe("deriveViewMode — aggregate command center collapsing to a focused single task", () => {
  it("collapses to focused when the mounted session is the only one with active work", () => {
    const mounted = { taskId: "task-1", sessionKey: "session-1" };
    const tasks = [task({ status: "running" })];
    expect(deriveViewMode(mounted, tasks)).toEqual({ mode: "focused", taskId: "task-1", sessionKey: "session-1" });
  });

  it("collapses to focused when other sessions exist but are all terminal", () => {
    const mounted = { taskId: "task-1", sessionKey: "session-1" };
    const tasks = [
      task({ status: "running" }),
      task({ taskId: "task-2", jobId: "task-2", sessionKey: "session-2", status: "done" }),
    ];
    expect(deriveViewMode(mounted, tasks).mode).toBe("focused");
  });

  it("renders aggregate, with the mounted session highlighted, when multiple sessions have active work", () => {
    const mounted = { taskId: "task-1", sessionKey: "session-1" };
    const tasks = [
      task({ status: "running" }),
      task({ taskId: "task-2", jobId: "task-2", sessionKey: "session-2", status: "blocked" }),
    ];
    expect(deriveViewMode(mounted, tasks)).toEqual({ mode: "aggregate", highlightSessionKey: "session-1" });
  });

  it("renders aggregate with no highlight when nothing is mounted (e.g. a stand-alone list_tasks view)", () => {
    expect(deriveViewMode(undefined, [task()])).toEqual({ mode: "aggregate", highlightSessionKey: undefined });
  });

  it("handles an empty task list gracefully (missing-metadata-shaped edge case)", () => {
    expect(deriveViewMode({ taskId: "t", sessionKey: "s" }, []).mode).toBe("focused");
    expect(deriveViewMode(undefined, []).mode).toBe("aggregate");
  });
});

describe("buildSessionRows — session-first rows keyed by sessionKey", () => {
  it("collapses multiple tasks in the same session to one row, keeping the most recent", () => {
    const tasks = [
      task({ taskId: "t1", jobId: "t1", lastEventAt: 1000, status: "done" }),
      task({ taskId: "t2", jobId: "t2", lastEventAt: 2000, status: "running" }),
    ];
    const rows = buildSessionRows(tasks);
    expect(rows).toHaveLength(1);
    expect(rows[0].latestTask.taskId).toBe("t2");
  });

  it("sorts by recency, newest first, with the highlighted session pinned to the top", () => {
    const rows = buildSessionRows(
      [
        task({ sessionKey: "old", lastEventAt: 1000 }),
        task({ sessionKey: "new", lastEventAt: 5000 }),
        task({ sessionKey: "mounted", lastEventAt: 500 }),
      ],
      { highlightSessionKey: "mounted" },
    );
    expect(rows.map((r) => r.sessionKey)).toEqual(["mounted", "new", "old"]);
  });

  it("marks the highlighted row expanded by default; others unexpanded", () => {
    const rows = buildSessionRows([task({ sessionKey: "a" }), task({ sessionKey: "b" })], { highlightSessionKey: "a" });
    expect(rows.find((r) => r.sessionKey === "a")?.expanded).toBe(true);
    expect(rows.find((r) => r.sessionKey === "b")?.expanded).toBe(false);
  });
});

describe("filterRows — Active default view + Recent view, exact status preserved underneath", () => {
  const rows = buildSessionRows([
    task({ sessionKey: "a", status: "running", lastEventAt: 3000 }),
    task({ sessionKey: "b", status: "blocked", lastEventAt: 2000 }),
    task({ sessionKey: "c", status: "done", lastEventAt: 1000 }),
    task({ sessionKey: "d", status: "failed", lastEventAt: 500 }),
  ]);

  it('"active" view (default) shows only Active + Needs attention groups', () => {
    const active = filterRows(rows, "active");
    expect(active.map((r) => r.sessionKey).sort()).toEqual(["a", "b"]);
  });

  it('"recent" view shows every group, and the underlying task.status is untouched', () => {
    const recent = filterRows(rows, "recent");
    expect(recent).toHaveLength(4);
    expect(recent.find((r) => r.sessionKey === "d")?.latestTask.status).toBe("failed");
  });

  it("the pinned (focused/mounted) session always shows in Active view even once it's terminal — a finished task must not disappear the moment it completes", () => {
    const active = filterRows(rows, "active", "c"); // "c" is done — terminal, normally filtered
    expect(active.map((r) => r.sessionKey).sort()).toEqual(["a", "b", "c"]);
  });

  it("pinning a session that's already visible in Active view doesn't duplicate it", () => {
    const active = filterRows(rows, "active", "a"); // "a" is running — already visible
    expect(active.filter((r) => r.sessionKey === "a")).toHaveLength(1);
  });

  it("with no pinned session, behavior is unchanged from the two-argument call", () => {
    expect(filterRows(rows, "active")).toEqual(filterRows(rows, "active", undefined));
  });
});

describe("expandSessionRow — expandable task history keyed by taskId", () => {
  it("attaches history from get_session(mode:\"tasks\"), grouped per entry, without touching the row's own fields", () => {
    const row = buildSessionRows([task({ sessionKey: "s", status: "running" })])[0];
    const history = [
      task({ taskId: "t1", jobId: "t1", sessionKey: "s", status: "done", summary: "first" }),
      task({ taskId: "t2", jobId: "t2", sessionKey: "s", status: "running" }),
    ];
    const expanded = expandSessionRow(row, history);
    expect(expanded.expanded).toBe(true);
    expect(expanded.history).toHaveLength(2);
    expect(expanded.history[0].group).toBe("completed");
    expect(expanded.history[0].title).toBe("first");
    expect(expanded.sessionKey).toBe(row.sessionKey);
  });
});

describe("mergePinnedDetail — regression coverage for the browser-smoke-caught bug", () => {
  // Deliberately TaskSummary-shaped fixtures (no `artifacts` field) — the
  // same shape a real list_tasks/get_session(mode:"tasks") call returns
  // (see packages/core/src/tools.ts's listTasks(), which never includes
  // artifacts). A fixture that accidentally carries artifacts on a
  // "non-pinned" task would hide exactly the bug this covers, the same way
  // an over-generous browser-harness mock did during manual verification.
  function summary(overrides = {}) {
    return { taskId: "s-task", jobId: "s-task", sessionKey: "s-1", agent: "assistant", status: "done", startedAt: 1, lastEventAt: 2, summary: "plain summary", ...overrides };
  }

  it("returns the list unchanged when there's no pinned detail yet", () => {
    const tasks = [summary()];
    expect(mergePinnedDetail(tasks, null)).toBe(tasks);
  });

  it("merges the full snapshot only into the task matching pinnedDetail's id — every other task stays a plain summary", () => {
    const pinned = summary({ taskId: "s-task", jobId: "s-task", artifacts: { prUrl: "https://x/pull/1", branchName: "fix/x" }, updates: [{ ts: 1, type: "tool", text: "did a thing" }] });
    const other = summary({ taskId: "other-task", jobId: "other-task", sessionKey: "s-2" });
    const merged = mergePinnedDetail([pinned, other], pinned);

    expect(merged[0].artifacts).toEqual({ prUrl: "https://x/pull/1", branchName: "fix/x" });
    expect(deriveTitle(merged[0])).toBe("PR: fix/x");

    // The regression itself: a non-pinned task must never pick up artifacts
    // it was never fetched with, and its title must stay summary-derived.
    expect(merged[1]).not.toHaveProperty("artifacts");
    expect(deriveTitle(merged[1])).toBe("plain summary");
  });

  it("matches by id across taskId/jobId naming (get_task uses taskId, list_tasks/get_session also expose jobId)", () => {
    const pinned = { jobId: "job-1", sessionKey: "s-1", status: "done", agent: "assistant", startedAt: 1, lastEventAt: 2, artifacts: { prUrl: "https://x/pull/2" } };
    const listEntry = summary({ taskId: "job-1", jobId: "job-1" });
    expect(mergePinnedDetail([listEntry], pinned)[0].artifacts).toBeDefined();
  });
});

describe("ensurePinnedTask — the pinned task survives dropping out of list_tasks(view:\"active\")", () => {
  it("merges, exactly like mergePinnedDetail, when the pinned task is still in the list", () => {
    const pinned = { taskId: "task-1", jobId: "task-1", sessionKey: "session-1", status: "running", startedAt: 1, lastEventAt: 9, artifacts: { prUrl: "https://x/pull/1" } };
    const result = ensurePinnedTask([task(), task({ taskId: "task-2", jobId: "task-2" })], pinned);
    expect(result).toHaveLength(2);
    expect(result[0].artifacts).toEqual({ prUrl: "https://x/pull/1" });
    expect(result[1].artifacts).toBeUndefined();
  });

  it("adds the pinned task when list_tasks has dropped it — a completed task must not vanish", () => {
    // The exact production sequence: the focused task completes, so the next
    // list_tasks(view:"active") no longer returns it. Merging alone would
    // silently render the user's just-finished task as gone.
    const finished = { taskId: "task-1", jobId: "task-1", sessionKey: "session-1", status: "done", agent: "assistant", startedAt: 1, lastEventAt: 9, summary: "Shipped it." };
    const activeOnly = [task({ taskId: "task-2", jobId: "task-2", sessionKey: "session-2" })];
    const result = ensurePinnedTask(activeOnly, finished);
    expect(result).toHaveLength(2);
    expect(result.find((t) => t.taskId === "task-1")).toEqual(finished);
  });

  it("is a no-op without a pinned detail, or when the pinned detail has no resolvable id", () => {
    const tasks = [task()];
    expect(ensurePinnedTask(tasks, null)).toBe(tasks);
    expect(ensurePinnedTask(tasks, { sessionKey: "session-1", status: "done" })).toBe(tasks);
  });

  it("never mutates the input list", () => {
    const tasks = [task()];
    ensurePinnedTask(tasks, { taskId: "other", jobId: "other", sessionKey: "s", status: "done", lastEventAt: 3 });
    expect(tasks).toHaveLength(1);
  });
});

describe("deriveCardTabs / defaultCardTab — inline card tabs, presence-driven", () => {
  it("offers response always, diagnostics only with real error detail, request only with a resolvable id", () => {
    expect(deriveCardTabs(task({ status: "running" }))).toEqual(["response", "request"]);
    expect(deriveCardTabs(task({ status: "failed", error: "boom" }))).toEqual(["response", "diagnostics", "request"]);
    expect(deriveCardTabs({ status: "done" })).toEqual(["response"]);
  });

  it("opens a failed task on its diagnostics — the answer the user came for", () => {
    expect(defaultCardTab(task({ status: "failed", error: "tsc exited 1" }))).toBe("diagnostics");
  });

  it("opens anything else on the response", () => {
    expect(defaultCardTab(task({ status: "running" }))).toBe("response");
    expect(defaultCardTab(task({ status: "done", summary: "Done." }))).toBe("response");
  });

  it("does not open a merely-blocked task on diagnostics — core sets .error to a session-busy message for status=\"blocked\" (deriveTaskStatus in packages/core/src/tools.ts), the same truthy-.error trap deriveTitle was fixed for", () => {
    const blocked = task({ status: "blocked", error: "session is busy with another task" });
    expect(deriveCardTabs(blocked)).toContain("diagnostics");
    expect(defaultCardTab(blocked)).toBe("response");
  });

  it("offers diagnostics on a failed status even when no error message landed, and still gates request on a resolvable id", () => {
    expect(deriveCardTabs({ status: "failed" })).toEqual(["response", "diagnostics"]);
    expect(defaultCardTab({ status: "failed" })).toBe("diagnostics");
  });

  it("never defaults to a tab it doesn't offer", () => {
    const doneNoId = { status: "done" };
    expect(deriveCardTabs(doneNoId)).toEqual(["response"]);
    expect(defaultCardTab(doneNoId)).toBe("response");
  });
});

describe("isLikelyMarkdown — plain prose stays plain", () => {
  it("is false for plain prose, empty, and non-string input", () => {
    expect(isLikelyMarkdown("Refactored the reconnect path and added a regression test.")).toBe(false);
    expect(isLikelyMarkdown("")).toBe(false);
    expect(isLikelyMarkdown(undefined)).toBe(false);
    expect(isLikelyMarkdown(null)).toBe(false);
  });

  it("is true for each structural marker the renderer actually handles", () => {
    expect(isLikelyMarkdown("## Summary\nDid the thing.")).toBe(true);
    expect(isLikelyMarkdown("- one\n- two")).toBe(true);
    expect(isLikelyMarkdown("1. first\n2. second")).toBe(true);
    expect(isLikelyMarkdown("> quoted")).toBe(true);
    expect(isLikelyMarkdown("run `pnpm build` first")).toBe(true);
    expect(isLikelyMarkdown("```\ncode\n```")).toBe(true);
    expect(isLikelyMarkdown("see [the PR](https://example.com/pull/1)")).toBe(true);
    expect(isLikelyMarkdown("this is **important**")).toBe(true);
    expect(isLikelyMarkdown("| a | b |\n| - | - |\n| 1 | 2 |")).toBe(true);
  });
});

describe("renderMarkdownHtml — escapes first, then emits only tags shell.html styles", () => {
  it("escapes HTML in the source so nothing in an agent summary can reach innerHTML as markup", () => {
    const html = renderMarkdownHtml('<img src=x onerror="alert(1)"> & done');
    expect(html).not.toContain("<img");
    expect(html).toContain("&lt;img");
    expect(html).toContain("&amp;");
  });

  it("escapes inside fenced code, list items, blockquotes, headings and table cells too — every block path", () => {
    expect(renderMarkdownHtml("```\n<script>x</script>\n```")).toContain("&lt;script&gt;");
    expect(renderMarkdownHtml("- <b>x</b>")).toContain("&lt;b&gt;");
    expect(renderMarkdownHtml("> <b>x</b>")).toContain("&lt;b&gt;");
    expect(renderMarkdownHtml("# <b>x</b>")).toContain("&lt;b&gt;");
    const table = renderMarkdownHtml("| <b>x</b> | y |\n| - | - |\n| <i>z</i> | w |");
    expect(table).toContain("&lt;b&gt;");
    expect(table).toContain("&lt;i&gt;");
    expect(table).not.toContain("<b>");
  });

  it("renders headings, paragraphs, lists, blockquotes and fenced code", () => {
    expect(renderMarkdownHtml("# Title")).toBe("<h1>Title</h1>");
    expect(renderMarkdownHtml("###### Deep")).toBe("<h3>Deep</h3>"); // only h1-h3 are styled
    expect(renderMarkdownHtml("one\ntwo\n\nthree")).toBe("<p>one two</p><p>three</p>");
    expect(renderMarkdownHtml("- a\n- b")).toBe("<ul><li>a</li><li>b</li></ul>");
    expect(renderMarkdownHtml("1. a\n2. b")).toBe("<ol><li>a</li><li>b</li></ol>");
    expect(renderMarkdownHtml("> quoted")).toBe("<blockquote>quoted</blockquote>");
    expect(renderMarkdownHtml("```ts\nconst x = 1;\n```")).toBe("<pre><code>const x = 1;</code></pre>");
  });

  it("renders a table with a header row and a divider", () => {
    const html = renderMarkdownHtml("| a | b |\n| --- | --- |\n| 1 | 2 |");
    expect(html).toBe("<table><thead><tr><th>a</th><th>b</th></tr></thead><tbody><tr><td>1</td><td>2</td></tr></tbody></table>");
  });

  it("renders inline code, bold, and italic — and treats markup inside a code span literally", () => {
    expect(renderMarkdownHtml("run `pnpm build`")).toBe("<p>run <code>pnpm build</code></p>");
    expect(renderMarkdownHtml("this is **important**")).toBe("<p>this is <strong>important</strong></p>");
    expect(renderMarkdownHtml("this is *subtle*")).toBe("<p>this is <em>subtle</em></p>");
    expect(renderMarkdownHtml("`**not bold**`")).toBe("<p><code>**not bold**</code></p>");
  });

  it("only links http/https/mailto — a javascript: href stays inert text", () => {
    expect(renderMarkdownHtml("[pr](https://example.com/pull/1)")).toContain('<a href="https://example.com/pull/1" target="_blank" rel="noopener noreferrer">pr</a>');
    const evil = renderMarkdownHtml("[click](javascript:alert(1))");
    expect(evil).not.toContain("<a ");
    expect(evil).toContain("[click]");
  });

  it("handles empty/missing input and an unterminated code fence without throwing", () => {
    expect(renderMarkdownHtml("")).toBe("");
    expect(renderMarkdownHtml(undefined)).toBe("");
    expect(renderMarkdownHtml("```\nunclosed")).toBe("<pre><code>unclosed</code></pre>");
  });
});

describe("bounded + deduplicated reads", () => {
  it("pollIntervalMs follows the attention-shaped cadence and stops at any terminal group", () => {
    expect(pollIntervalMs("active")).toBe(2500);
    expect(pollIntervalMs("needs_attention")).toBe(8000);
    expect(pollIntervalMs("completed")).toBeNull();
    expect(pollIntervalMs("failed")).toBeNull();
  });

  it("pollIntervalMs backs off on repeated failures, capped at 30s", () => {
    expect(pollIntervalMs("active", 1)).toBe(5000);
    expect(pollIntervalMs("active", 10)).toBe(30000);
  });

  it("shouldPoll refuses to start a second read while one is already in flight (dedup)", () => {
    expect(shouldPoll({ pollInFlight: true, tasks: [task({ status: "running" })] })).toBe(false);
  });

  it("shouldPoll stops once every task in scope is terminal (bound)", () => {
    expect(shouldPoll({ pollInFlight: false, tasks: [task({ status: "done" }), task({ status: "failed" })] })).toBe(false);
  });

  it("shouldPoll allows one read when nothing is known yet, and continues while anything is non-terminal", () => {
    expect(shouldPoll({ pollInFlight: false, tasks: [] })).toBe(true);
    expect(shouldPoll({ pollInFlight: false, tasks: [task({ status: "running" })] })).toBe(true);
  });

  it("preferSnapshot never lets a stale non-terminal read overwrite an already-terminal one", () => {
    const terminal = task({ status: "done", lastEventAt: 1000 });
    const staleRunning = task({ status: "running", lastEventAt: 5000 }); // newer timestamp, but non-terminal
    expect(preferSnapshot(staleRunning, terminal)).toBe(terminal);
  });

  it("preferSnapshot prefers the newer of two non-terminal (or two terminal) reads", () => {
    const older = task({ status: "running", lastEventAt: 1000 });
    const newer = task({ status: "running", lastEventAt: 2000 });
    expect(preferSnapshot(newer, older)).toBe(newer);
    expect(preferSnapshot(older, newer)).toBe(newer);
  });

  it("preferSnapshot with no current snapshot just takes the first read", () => {
    const first = task();
    expect(preferSnapshot(first, undefined)).toBe(first);
  });
});

describe("conversation scope fallback", () => {
  it("defaults to this card instance's own known sessions, not a true conversation-wide claim", () => {
    const scope = resolveScope(["s1", "s2", "s1"], false);
    expect(scope).toEqual({ scoped: true, sessionKeys: ["s1", "s2"] });
    const tasks = [task({ sessionKey: "s1" }), task({ sessionKey: "s3" })];
    expect(filterTasksByScope(tasks, scope).map((t) => t.sessionKey)).toEqual(["s1"]);
  });

  it("explicit All activity opts out of scoping entirely", () => {
    const scope = resolveScope(["s1"], true);
    expect(scope).toEqual({ scoped: false, sessionKeys: null });
    const tasks = [task({ sessionKey: "s1" }), task({ sessionKey: "unrelated" })];
    expect(filterTasksByScope(tasks, scope)).toHaveLength(2);
  });
});

describe("compact selection policy", () => {
  it("holds the current selection while it still has work in view", () => {
    const tasks = [task({ sessionKey: "s1" }), task({ sessionKey: "s2", lastEventAt: 9000 })];
    expect(resolveCompactSelection(null, tasks, "s1")).toBe("s1");
  });

  it("keeps the mounted session pinned even once it drops out of list_tasks(view:\"active\")", () => {
    const tasks = [task({ sessionKey: "other", lastEventAt: 9000 })];
    expect(resolveCompactSelection({ sessionKey: "mine" }, tasks, "mine")).toBe("mine");
  });

  it("re-runs from scratch when the pinned session is gone — the Task Center round trip", () => {
    // s1 vanished while the Task Center was open; the pin must move to real
    // live work rather than pointing at a session with no rows behind it.
    const tasks = [task({ sessionKey: "s2", lastEventAt: 2000 }), task({ sessionKey: "s3", lastEventAt: 3000 })];
    expect(resolveCompactSelection(null, tasks, "s1")).toBe("s3");
  });

  it("leaves a terminal-only card unpinned rather than resurrecting finished work", () => {
    // A pin forces its row past the Active filter (filterRows), so pinning
    // here would show completed work on a card nobody pointed at it.
    const tasks = [task({ sessionKey: "s2", status: "done", lastEventAt: 3000 })];
    expect(resolveCompactSelection(null, tasks, "s1")).toBeUndefined();
    expect(resolveCompactSelection(null, [], null)).toBeUndefined();
  });
});

describe("get_task payload discrimination", () => {
  it("accepts a real snapshot and rejects the not-found envelope that carries the same id", () => {
    expect(isTaskSnapshot(task())).toBe(true);
    // app.ts's reply for a pruned or unauthorized id.
    expect(isTaskSnapshot({ taskId: "task-1", status: "error", error: "Task not found." })).toBe(false);
    expect(isTaskSnapshot(null)).toBe(false);
    expect(isTaskSnapshot({ sessionKey: "s1", status: "running" })).toBe(false);
  });

  it("keeps a genuinely errored job, because \"error\" is a real JobStatus", () => {
    // Discriminating on status would throw away the failed run whose
    // diagnostics the card exists to show.
    expect(isTaskSnapshot(task({ status: "error", error: "boom" }))).toBe(true);
  });

  it("a rejected envelope leaves the retained row untouched", () => {
    const known = task({ taskId: "a", jobId: "a", status: "done", summary: "All finished" });
    // Deliberately not a WidgetTask — no sessionKey — which is exactly what
    // isTaskSnapshot detects, so the cast is the point of the fixture.
    const envelope = { taskId: "a", status: "error", error: "Task not found." } as unknown as Parameters<typeof ensurePinnedTask>[1];
    const detail = isTaskSnapshot(envelope) ? envelope : null;
    expect(ensurePinnedTask([known], detail)).toEqual([known]);
  });
});

describe("resume reconciliation", () => {
  it("keeps known live work during a transient empty list response", () => {
    const live = task({ status: "running" });
    expect(reconcileTaskList([live], [])).toEqual([live]);
  });

  it("accepts an empty list after all known work is terminal", () => {
    expect(reconcileTaskList([task({ status: "done" })], [])).toEqual([]);
  });

  it("retains a task the incoming read omits, so finishing work stays visible", () => {
    // list_tasks drops a task the instant it finishes (and the server can prune
    // one outright). With other work still active the read is non-empty, so
    // replacing wholesale dropped the finished run entirely and the card lost
    // the summary the user was waiting for.
    const finished = task({ taskId: "a", jobId: "a", status: "done" });
    const stillRunning = task({ taskId: "b", jobId: "b", status: "running" });
    const merged = reconcileTaskList([finished, stillRunning], [stillRunning]);
    expect(merged.map((t) => t.taskId).sort((x, y) => String(x).localeCompare(String(y)))).toEqual(["a", "b"]);
  });

  it("lets the incoming read win for a task it does contain", () => {
    const before = task({ taskId: "a", jobId: "a", status: "running" });
    const after = task({ taskId: "a", jobId: "a", status: "done" });
    expect(reconcileTaskList([before], [after])).toEqual([after]);
  });

  it("does not duplicate a task present in both lists", () => {
    const t = task({ taskId: "a", jobId: "a", status: "running" });
    expect(reconcileTaskList([t], [t])).toHaveLength(1);
  });

  it("bounds retention to the sessions the card knows about", () => {
    // The read is unscoped (view:"all", so state is complete and the view
    // filters). Without a bound, retention would accumulate every conversation's
    // tasks for the life of the card and shouldPoll would never settle. Foreign
    // sessions are re-supplied whole by each read, which is all the Task Center
    // needs.
    const mine = task({ taskId: "a", jobId: "a", sessionKey: "mine", status: "done" });
    const foreign = task({ taskId: "z", jobId: "z", sessionKey: "theirs", status: "running" });
    const incoming = [task({ taskId: "b", jobId: "b", sessionKey: "mine", status: "running" })];
    const merged = reconcileTaskList([mine, foreign], incoming, ["mine"]);
    expect(merged.map((t) => t.taskId).sort((x, y) => String(x).localeCompare(String(y)))).toEqual(["a", "b"]);
  });

  it("retains everything when no bound is given", () => {
    const foreign = task({ taskId: "z", jobId: "z", sessionKey: "theirs", status: "running" });
    const incoming = [task({ taskId: "b", jobId: "b", sessionKey: "mine", status: "running" })];
    expect(reconcileTaskList([foreign], incoming).map((t) => t.taskId).sort((x, y) => String(x).localeCompare(String(y)))).toEqual(["b", "z"]);
  });
});

describe("inline card tabs", () => {
  it("keeps Response and Request stable, adding Diagnostics only for attention states", () => {
    expect(deriveCardTabs(task({ status: "done" }))).toEqual(["response", "request"]);
    expect(deriveCardTabs(task({ status: "failed" }))).toEqual(["response", "diagnostics", "request"]);
  });

  it("defaults successful terminal runs to Response and supports roving keyboard navigation", () => {
    expect(defaultCardTab(task({ status: "done" }))).toBe("response");
    const tabs = ["response", "request"];
    expect(nextCardTab(tabs, "response", "ArrowRight")).toBe("request");
    expect(nextCardTab(tabs, "request", "ArrowLeft")).toBe("response");
    expect(nextCardTab(tabs, "response", "End")).toBe("request");
    expect(nextCardTab(tabs, "request", "Home")).toBe("response");
  });
});

describe("formatElapsed", () => {
  it("formats seconds, minutes, and hours", () => {
    expect(formatElapsed(5_000)).toBe("5s");
    expect(formatElapsed(90_000)).toBe("1m 30s");
    expect(formatElapsed(3 * 60 * 60_000 + 5 * 60_000)).toBe("3h 5m");
  });

  it("handles zero/negative/non-finite gracefully rather than throwing", () => {
    expect(formatElapsed(0)).toBe("0s");
    expect(formatElapsed(-5)).toBe("0s");
    expect(formatElapsed(NaN)).toBe("0s");
  });
});

describe("isStale / deriveActivityLabel — a liveness claim paired with the evidence behind it", () => {
  it("stays quiet-free until the server's own first upstream check could have run", () => {
    // The old threshold was 90s, but core does not ask upstream whether the run
    // is alive until RECONCILE_QUIET_MS (120s) — so anything below that accused
    // a task before a single thing had looked at it.
    const now = 200_000;
    expect(isStale(now - 91_000, now)).toBe(false);
    expect(isStale(now - 121_000, now)).toBe(true);
  });

  it("an active task well within the threshold reads as active, with elapsed time as evidence", () => {
    const now = 100_000;
    expect(deriveActivityLabel(task({ status: "running", lastEventAt: now - 5_000 }), now)).toBe("active 5s ago");
  });

  it("a quiet task is reported as quiet, not accused — silence alone is never stalling", () => {
    const now = 900_000;
    // Quiet well past the old 90s threshold, and past the stalled threshold too,
    // but nothing has checked: the honest answer is "quiet", not "stuck".
    expect(deriveActivityLabel(task({ status: "running", lastEventAt: now - 600_000 }), now)).toBe(
      "working quietly · last activity 10m 0s ago",
    );
  });

  it("stays quiet when the server's check found the run genuinely alive, however long the silence", () => {
    const now = 900_000;
    const alive = { checkedAt: now - 30_000, upstream: "active", producing: false };
    expect(deriveActivityLabel(task({ status: "running", lastEventAt: now - 600_000, liveness: alive }), now)).toBe(
      "working quietly · last activity 10m 0s ago",
    );
    const producing = { checkedAt: now - 30_000, upstream: "unknown", producing: true };
    expect(deriveActivityLabel(task({ status: "running", lastEventAt: now - 600_000, liveness: producing }), now)).toBe(
      "working quietly · last activity 10m 0s ago",
    );
  });

  it("claims stalled only when a fresh check found nothing AND the silence outlasted the stalled threshold", () => {
    const now = 900_000;
    const foundNothing = { checkedAt: now - 30_000, upstream: "unknown", producing: false };
    // Every signal agrees: checked recently, no active run, no transcript
    // progress, and quiet for longer than a normal silent stretch.
    expect(
      deriveActivityLabel(task({ status: "running", lastEventAt: now - 600_000, liveness: foundNothing }), now),
    ).toBe("possibly stalled · no activity for 10m 0s");

    // Same empty check, but the silence is still within normal range.
    expect(
      deriveActivityLabel(task({ status: "running", lastEventAt: now - 180_000, liveness: foundNothing }), now),
    ).toBe("working quietly · last activity 3m 0s ago");

    // A stale check says nothing about the run's state now, so it cannot accuse.
    const staleCheck = { checkedAt: now - 600_000, upstream: "unknown", producing: false };
    expect(
      deriveActivityLabel(task({ status: "running", lastEventAt: now - 600_000, liveness: staleCheck }), now),
    ).toBe("working quietly · last activity 10m 0s ago");
  });

  it("a terminal task reads as finished, not active/stale", () => {
    const now = 100_000;
    expect(deriveActivityLabel(task({ status: "done", lastEventAt: now - 5_000 }), now)).toBe("finished 5s ago");
  });
});

describe("deriveConnectionNotice — the task, the connector, and the chat stream are three different things", () => {
  it("uses the connector-native transcript state instead of inferring execution failure", () => {
    expect(deriveConnectionNotice({ upstream: "reconnecting", transcript: "detached" })).toMatchObject({
      stream: "detached",
      text: expect.stringMatching(/may still be running upstream/i),
    });
    expect(deriveConnectionNotice({ upstream: "reconnecting", transcript: "replaying" })).toMatchObject({
      stream: "replaying",
      text: expect.stringMatching(/replaying missed/i),
    });
    expect(deriveConnectionNotice({ upstream: "unavailable", transcript: "detached" })).toMatchObject({
      stream: "detached",
      text: expect.stringMatching(/will not assume the task stopped/i),
    });
  });

  it("says nothing when everything is nominal", () => {
    expect(deriveConnectionNotice({ pollFailures: 0, recovery: null })).toEqual({
      connector: "connected",
      stream: "active",
      text: null,
    });
    expect(deriveConnectionNotice()).toEqual({ connector: "connected", stream: "active", text: null });
  });

  it("reports a dead chat stream as the task still running, never as a bare interruption", () => {
    // This is the case that read as failure: the reply that dispatched the work
    // ended before the answer arrived, and the job is explicitly still going.
    for (const reason of ["no_live_final_text", "parent_observation_timeout"]) {
      const notice = deriveConnectionNotice({ pollFailures: 0, recovery: { reason } });
      expect(notice.stream).toBe("interrupted");
      expect(notice.connector).toBe("connected"); // the connector is fine — don't blame it
      expect(notice.text).toContain("still running");
      expect(notice.text).not.toMatch(/failed|error|interrupted\.$/i);
    }
  });

  it("keeps connector trouble separate from stream trouble, and tolerates one blip", () => {
    expect(deriveConnectionNotice({ pollFailures: 1 }).text).toBeNull(); // a single miss is not news
    const flaky = deriveConnectionNotice({ pollFailures: 3 });
    expect(flaky).toMatchObject({ connector: "reconnecting", stream: "active" });
    expect(flaky.text).toContain("keeps running");
  });

  it("an unrecognized recovery reason does not get reported as a dead stream", () => {
    expect(deriveConnectionNotice({ recovery: { reason: "something-else" } })).toMatchObject({
      stream: "active",
      text: null,
    });
  });
});

describe("deriveTimeline / deriveLatestUpdate — the actual evidence, not just a status label", () => {
  const logs = [
    { ts: 1000, type: "lifecycle", text: "Started" },
    { ts: 1200, type: "tool", text: "Reading files" },
    { ts: 1400, type: "tool", text: "Reading files" },
    { ts: 1600, type: "tool", text: "Reading files" },
    { ts: 1800, type: "tool-result", text: "3 files read" },
    { ts: 2000, type: "tool", text: "Running command: pnpm test" },
  ];

  it("collapses consecutive identical entries into one row with a count, instead of spamming duplicates", () => {
    const timeline = deriveTimeline(logs, 10);
    const readingFiles = timeline.find((row) => row.text === "Reading files");
    expect(readingFiles?.count).toBe(3);
  });

  it("returns at most maxRows, most recent first", () => {
    const timeline = deriveTimeline(logs, 2);
    expect(timeline).toHaveLength(2);
    expect(timeline[0].text).toBe("Running command: pnpm test");
  });

  it("keeps lifecycle rows neutral and marks only explicit tool errors", () => {
    const timeline = deriveTimeline([
      { ts: 1000, type: "lifecycle", text: "Agent lifecycle: end" },
      { ts: 1100, type: "tool-result", text: "Bash failed", isError: true },
    ], 10);
    expect(timeline[1].isError).toBe(false);
    expect(timeline[0].isError).toBe(true);
  });

  it("returns an empty array for missing/empty logs rather than throwing", () => {
    expect(deriveTimeline(undefined)).toEqual([]);
    expect(deriveTimeline([])).toEqual([]);
  });

  it("deriveLatestUpdate returns the single most recent entry", () => {
    expect(deriveLatestUpdate(logs)).toEqual({ ts: 2000, type: "tool", text: "Running command: pnpm test" });
    expect(deriveLatestUpdate([])).toBeNull();
  });
});

describe("mergeRingBuffer — client-side accumulation of check_task/get_task's now-bounded per-poll delta", () => {
  it("appends a delta onto the existing buffer", () => {
    const existing = [{ ts: 1, type: "lifecycle", text: "a", seq: 1 }];
    const delta = [{ ts: 2, type: "lifecycle", text: "b", seq: 2 }];
    expect(mergeRingBuffer(existing, delta)).toEqual([...existing, ...delta]);
  });

  it("caps the merged buffer at RING_BUFFER_MAX, dropping the oldest first", () => {
    const existing = Array.from({ length: RING_BUFFER_MAX }, (_, i) => ({ ts: i, type: "lifecycle", text: `e${i}`, seq: i + 1 }));
    const delta = [{ ts: 999, type: "lifecycle", text: "new", seq: RING_BUFFER_MAX + 1 }];
    const merged = mergeRingBuffer(existing, delta);
    expect(merged.length).toBe(RING_BUFFER_MAX);
    expect(merged.at(-1)?.text).toBe("new");
    expect(merged[0].text).toBe("e1"); // e0 dropped to make room
  });

  it("an empty delta is a no-op, returning the same buffer", () => {
    const existing = [{ ts: 1, type: "lifecycle", text: "a", seq: 1 }];
    expect(mergeRingBuffer(existing, [])).toBe(existing);
    expect(mergeRingBuffer(existing, undefined)).toBe(existing);
  });

  it("treats a missing/undefined existing buffer as empty", () => {
    const delta = [{ ts: 1, type: "lifecycle", text: "a", seq: 1 }];
    expect(mergeRingBuffer(undefined, delta)).toEqual(delta);
  });

  it("deduplicates by seq — a defensive guard against overlapping reads racing", () => {
    const existing = [{ ts: 1, type: "lifecycle", text: "a", seq: 1 }];
    const delta = [{ ts: 1, type: "lifecycle", text: "a", seq: 1 }, { ts: 2, type: "lifecycle", text: "b", seq: 2 }];
    expect(mergeRingBuffer(existing, delta)).toEqual([
      { ts: 1, type: "lifecycle", text: "a", seq: 1 },
      { ts: 2, type: "lifecycle", text: "b", seq: 2 },
    ]);
  });
});

describe("shouldRenderImmediately — lifecycle/terminal changes render now, cosmetic activity can debounce", () => {
  it("the first render (no prior group) is always immediate", () => {
    expect(shouldRenderImmediately(null, "active")).toBe(true);
  });

  it("a status-group transition is always immediate", () => {
    expect(shouldRenderImmediately("active", "completed")).toBe(true);
    expect(shouldRenderImmediately("active", "needs_attention")).toBe(true);
  });

  it("the same group as last render is not immediate — cosmetic activity may debounce", () => {
    expect(shouldRenderImmediately("active", "active")).toBe(false);
  });
});

describe("collectFollowUpWakes — once-per-transition host nudges", () => {
  it("seeds first sight without waking (hydrate of an already-terminal card stays quiet)", () => {
    const priorGroups = new Map();
    const alreadyWoken = new Set();
    const first = collectFollowUpWakes({
      tasks: [task({ taskId: "t1", status: "completed" })],
      priorGroups,
      alreadyWoken,
    });
    expect(first.wakes).toEqual([]);
    expect(first.priorGroups.get("t1")).toBe("completed");
  });

  it("wakes once when a seeded task enters needs_attention, completed, or failed", () => {
    const priorGroups = new Map([["t1", "active"]]);
    const alreadyWoken = new Set();
    for (const [status, group] of [
      ["needs-human", "needs_attention"],
      ["completed", "completed"],
      ["failed", "failed"],
    ]) {
      const { wakes } = collectFollowUpWakes({
        tasks: [task({ taskId: "t1", sessionKey: "s1", status })],
        priorGroups: new Map(priorGroups),
        alreadyWoken,
      });
      expect(wakes).toHaveLength(1);
      expect(wakes[0]?.group).toBe(group);
      expect(wakes[0]?.prompt).toContain("check_task");
      expect(wakes[0]?.prompt).toContain("t1");
      expect(wakes[0]?.prompt).toContain("sessionKey: s1");
    }
  });

  it("does not re-wake the same taskId+group, and ignores same-group status renames", () => {
    const priorGroups = new Map([["t1", "active"]]);
    const alreadyWoken = new Set();
    const intoNeeds = collectFollowUpWakes({
      tasks: [task({ taskId: "t1", status: "needs-human" })],
      priorGroups,
      alreadyWoken,
    });
    expect(intoNeeds.wakes).toHaveLength(1);
    alreadyWoken.add(intoNeeds.wakes[0]!.key);
    const stillNeeds = collectFollowUpWakes({
      tasks: [task({ taskId: "t1", status: "blocked" })],
      priorGroups: intoNeeds.priorGroups,
      alreadyWoken,
    });
    expect(stillNeeds.wakes).toEqual([]);
    const replay = collectFollowUpWakes({
      tasks: [task({ taskId: "t1", status: "needs-human" })],
      priorGroups: new Map([["t1", "active"]]),
      alreadyWoken,
    });
    expect(replay.wakes).toEqual([]);
  });

  it("does not wake on active-only transitions", () => {
    const { wakes } = collectFollowUpWakes({
      tasks: [task({ taskId: "t1", status: "queued" })],
      priorGroups: new Map([["t1", "active"]]),
      alreadyWoken: new Set(),
    });
    expect(wakes).toEqual([]);
  });
});

describe("deriveStatusPill — status communicated by icon + text, never color alone", () => {
  it("returns a distinct icon and label for every group", () => {
    const pills = ["active", "needs_attention", "completed", "failed"].map(deriveStatusPill);
    expect(new Set(pills.map((p) => p.icon)).size).toBe(4);
    expect(new Set(pills.map((p) => p.label)).size).toBe(4);
    expect(pills.every((p) => typeof p.icon === "string" && typeof p.label === "string")).toBe(true);
  });
});

describe("deriveCounts / formatCounts — the inline card's compact session summary", () => {
  const history = [
    task({ status: "running" }),
    task({ status: "done" }),
    task({ status: "done" }),
    task({ status: "blocked" }),
    task({ status: "failed" }),
  ];

  it("counts every group plus a total", () => {
    expect(deriveCounts(history)).toEqual({ active: 1, needs_attention: 1, completed: 2, failed: 1, total: 5 });
  });

  it("handles missing/empty history without throwing", () => {
    expect(deriveCounts(undefined)).toEqual({ active: 0, needs_attention: 0, completed: 0, failed: 0, total: 0 });
    expect(deriveCounts([])).toEqual({ active: 0, needs_attention: 0, completed: 0, failed: 0, total: 0 });
  });

  it("formats only the non-zero groups, in a fixed order, joined compactly", () => {
    expect(formatCounts(deriveCounts(history))).toBe("1 running · 1 needs attention · 2 completed · 1 failed");
    expect(formatCounts(deriveCounts([task({ status: "done" })]))).toBe("1 completed");
  });

  it("formats to an empty string for no history — the caller decides what to show instead", () => {
    expect(formatCounts(deriveCounts([]))).toBe("");
  });
});

describe("deriveDelegationIdentity — who is actually doing the work, by id", () => {
  const attached = (extra = {}) => ({
    id: "att-1",
    runtime: "claude-fleet",
    handle: "t3-fleet-run-ccc4f7df7ace97de1cd45fafef4b2512",
    providerSessionId: "coding-9f2b1c",
    worktree: "/Users/x/.t3-fleet-worktrees/clawconnect-recovery-fix",
    host: "build-host",
    status: "running",
    ...extra,
  });

  it("returns null for an ordinary turn, so a plain card grows no empty block", () => {
    expect(deriveDelegationIdentity(task({}))).toBeNull();
    expect(deriveDelegationIdentity({})).toBeNull();
    expect(deriveDelegationIdentity(undefined)).toBeNull();
  });

  it("surfaces the Fleet run and coding-session ids VERBATIM — a truncated id cannot be looked up", () => {
    const identity = deriveDelegationIdentity(task({ agentSession: attached() }));
    expect(identity).toEqual({
      runtime: "claude-fleet",
      fleetRunId: "t3-fleet-run-ccc4f7df7ace97de1cd45fafef4b2512",
      codingSessionId: "coding-9f2b1c",
      worktree: "/Users/x/.t3-fleet-worktrees/clawconnect-recovery-fix",
      host: "build-host",
      status: "running",
    });
    // The exact failure this exists to prevent: recognising an id is not the
    // same as being able to use it.
    expect(identity?.fleetRunId).toHaveLength("t3-fleet-run-ccc4f7df7ace97de1cd45fafef4b2512".length);
  });

  it("degrades field by field rather than dropping the whole block", () => {
    const identity = deriveDelegationIdentity(
      task({ agentSession: { id: "a", runtime: "claude-fleet", handle: "run-1", status: "running" } }),
    );
    expect(identity?.fleetRunId).toBe("run-1");
    expect(identity?.codingSessionId).toBeNull();
    expect(identity?.worktree).toBeNull();
  });

  it("needs a handle to be worth showing — an attachment with no id identifies nothing", () => {
    expect(deriveDelegationIdentity(task({ agentSession: { id: "a", runtime: "claude-fleet", status: "running" } }))).toBeNull();
  });
});

describe("deriveUpstreamEvidence — dated evidence, never a manufactured confirmation", () => {
  const NOW = 1_000_000;

  it("reports a fresh check with its age rather than as a present-tense fact", () => {
    const evidence = deriveUpstreamEvidence(
      task({ liveness: { checkedAt: NOW - 30_000, upstream: "active", producing: false }, parentRunId: "run-abc" }),
      NOW,
    );
    expect(evidence.upstream).toBe("run executing");
    expect(evidence.checkedAgo).toBe("30s ago");
    expect(evidence.runId).toBe("run-abc");
  });

  it("drops a stale claim entirely instead of showing it as current", () => {
    // Past LIVENESS_FRESH_MS (5 min): the run may well still be executing, but
    // nobody has confirmed it, and saying so would invent a confirmation.
    const evidence = deriveUpstreamEvidence(
      task({ liveness: { checkedAt: NOW - 6 * 60_000, upstream: "active", producing: false } }),
      NOW,
    );
    expect(evidence.upstream).toBeNull();
    expect(evidence.checkedAgo).toBeNull();
  });

  it("distinguishes no-positive-signal from active — `unknown` is not evidence of the opposite", () => {
    const evidence = deriveUpstreamEvidence(
      task({ liveness: { checkedAt: NOW - 1_000, upstream: "unknown", producing: false } }),
      NOW,
    );
    expect(evidence.upstream).toBe("no positive signal");
  });

  it("states what recovery is DOING, and that upstream may still be active", () => {
    const evidence = deriveUpstreamEvidence(task({ recovery: { reason: "no_live_final_text" } }), NOW);
    expect(evidence.recoveryAction).toMatch(/may still be active/i);
    expect(deriveUpstreamEvidence(task({}), NOW).recoveryAction).toBeNull();
  });
});

describe("deriveCardTabs — a healthy delegated run still has ids worth reaching", () => {
  it("offers diagnostics for a delegated turn that has not failed", () => {
    const delegated = task({
      status: "running",
      agentSession: { id: "a", runtime: "claude-fleet", handle: "run-1", status: "running" },
    });
    expect(deriveCardTabs(delegated)).toContain("diagnostics");
    // ...without pretending it failed: the card still opens on the response.
    expect(defaultCardTab(delegated)).toBe("response");
  });

  it("still offers no diagnostics tab for an ordinary healthy turn", () => {
    expect(deriveCardTabs(task({ status: "running" }))).not.toContain("diagnostics");
  });
});

describe("normalizeDiagnostics — one place to read a failure from", () => {
  it("lifts get_task's nested diagnostics block to the top level the rest of the card reads", () => {
    const normalized = normalizeDiagnostics({
      taskId: "t1",
      status: "failed",
      diagnostics: {
        error: "Stopped watching after 90m",
        errorInfo: { category: "timeout", suggestedRecovery: "Do not re-submit on this session" },
        recovery: { reason: "no_live_final_text" },
      },
    });
    expect(normalized?.error).toBe("Stopped watching after 90m");
    expect(normalized?.errorInfo).toEqual({ category: "timeout", suggestedRecovery: "Do not re-submit on this session" });
    expect(normalized?.recovery).toEqual({ reason: "no_live_final_text" });
  });

  it("never blanks an already-merged row: top level wins over an empty diagnostics block", () => {
    const normalized = normalizeDiagnostics({
      error: "session busy",
      diagnostics: { error: undefined, errorInfo: undefined },
    });
    expect(normalized?.error).toBe("session busy");
  });

  it("passes through anything without a diagnostics block, including null/undefined", () => {
    const plain = { taskId: "t1", status: "running" };
    expect(normalizeDiagnostics(plain)).toBe(plain);
    expect(normalizeDiagnostics(null)).toBeNull();
    expect(normalizeDiagnostics(undefined)).toBeUndefined();
  });
});
